[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "src/app/api"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs"
